import { Transaction } from './monzo.state';

export const testTransactions: Transaction[] = [
    {
        'id': 'tx_00009H5HjXaNFk9bUSaeNl',
        'created': '2017-02-04T11:30:29.227Z',
        'description': 'Initial top up',
        'amount': 10000,
        'fees': {},
        'currency': 'GBP',
        'merchant': null,
        'notes': '',
        'metadata': {
            'is_topup': 'true',
            'stripe_card_last_four': '1679',
            'stripe_charge_id': 'ch_19j3UQGFdNCyIQQUQUwaMo6K'
        },
        'labels': null,
        'account_balance': 10000,
        'attachments': [],
        'international': null,
        'category': 'mondo',
        'is_load': true,
        'settled': '2017-02-04T11:30:29.227Z',
        'local_amount': 10000,
        'local_currency': 'GBP',
        'updated': '2017-02-04T11:30:29.504Z',
        'account_id': 'acc_00009H32tRh67o0CTFpYeH',
        'user_id': '',
        'counterparty': {},
        'scheme': 'gps_mastercard',
        'dedupe_id': '216684574208537951',
        'originator': false,
        'include_in_spending': false,
        'can_be_excluded_from_breakdown': false,
        'can_be_made_subscription': false,
        'can_split_the_bill': false
    },
    {
        'id': 'tx_00009H5IYVnPfOIUv2aFQP',
        'created': '2017-02-04T11:39:41.86Z',
        'description': 'GOOGLE *SERVICES       g.co/payhelp GBR',
        'amount': -100,
        'fees': {},
        'currency': 'GBP',
        'merchant': 'merch_000095WJNLQgevMrNEbwvp',
        'notes': '',
        'metadata': {},
        'labels': null,
        'account_balance': 9900,
        'attachments': [],
        'international': null,
        'category': 'general',
        'is_load': false,
        'settled': '',
        'local_amount': -100,
        'local_currency': 'GBP',
        'updated': '2017-02-04T11:39:42.134Z',
        'account_id': 'acc_00009H32tRh67o0CTFpYeH',
        'user_id': '',
        'counterparty': {},
        'scheme': 'gps_mastercard',
        'dedupe_id': '216684574170204627951004470',
        'originator': false,
        'include_in_spending': true,
        'can_be_excluded_from_breakdown': true,
        'can_be_made_subscription': false,
        'can_split_the_bill': false
    },
    {
        'id': 'tx_00009H5JuKDHVl7l5zoEKH',
        'created': '2017-02-04T11:54:50.493Z',
        'description': 'GOOGLE *SERVICES       g.co/payhelp GBR',
        'amount': 100,
        'fees': {},
        'currency': 'GBP',
        'merchant': 'merch_00009BoOqj3y8xf0LfclCT',
        'notes': '',
        'metadata': {},
        'labels': null,
        'account_balance': 10000,
        'attachments': [],
        'international': null,
        'category': 'general',
        'is_load': false,
        'settled': '',
        'local_amount': 100,
        'local_currency': 'GBP',
        'updated': '2017-02-04T11:54:50.965Z',
        'account_id': 'acc_00009H32tRh67o0CTFpYeH',
        'user_id': '',
        'counterparty': {},
        'scheme': 'gps_mastercard',
        'dedupe_id': '208547058',
        'originator': false,
        'include_in_spending': true,
        'can_be_excluded_from_breakdown': false,
        'can_be_made_subscription': false,
        'can_split_the_bill': false
    }
];
